package tela;

/**
 *
 * @author Thiágo
 */
import entidade.AluguelQuarto;
import entidade.Quarto;
import dao.AluguelDAO;
import entidade.Hospede;
import org.jdesktop.layout.GroupLayout;

public class CadastrarAluguel extends javax.swing.JFrame {
    private boolean editando = false;
    private AluguelQuarto aluguel = new AluguelQuarto();
    private Hospede hospede = new Hospede();
    private Quarto quarto = new Quarto();

    /** Creates new form CadastrarAluguel */
    public CadastrarAluguel() {
        initComponents();
    }
    
    public CadastrarAluguel(boolean editando, AluguelQuarto aluguel){
        initComponents();
        this.editando = editando;
        this.aluguel = aluguel;
        
        jTextFieldCodigo.setText(String.valueOf(aluguel.getCodigo()));
        if (editando){
            jTextFieldCodigo.setEditable(false);
            jTextFieldCodigoHospede.setEditable(false);
            jTextFieldCodigoQuarto.setEditable(false);
        }
        jTextFieldEntradaDia.setText(aluguel.getEntradaDia());
        jTextFieldEntradaHora.setText(aluguel.getEntradaHora());
        jTextFieldSaidaDia.setText(aluguel.getSaidaDia());
        jTextFieldSaidaHora.setText(aluguel.getSaidaHora());
        jTextFieldCodigoHospede.setText(String.valueOf(aluguel.getHospede().getCodigo()));
        jTextFieldCodigoQuarto.setText(String.valueOf(aluguel.getQuarto().getCodigo()));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldCodigo = new javax.swing.JTextField();
        jTextFieldEntradaDia = new javax.swing.JTextField();
        jTextFieldEntradaHora = new javax.swing.JTextField();
        jTextFieldSaidaDia = new javax.swing.JTextField();
        jTextFieldSaidaHora = new javax.swing.JTextField();
        jLabelCodigo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonSalvar = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        jTextFieldCodigoHospede = new javax.swing.JTextField();
        jTextFieldCodigoQuarto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldEntradaHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEntradaHoraActionPerformed(evt);
            }
        });

        jLabelCodigo.setText("Código");

        jLabel3.setText("Data de Entrada");

        jLabel4.setText("Hora de Entrada");

        jLabel5.setText("Data de Saída");

        jLabel6.setText("Hora de Saída");

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        jLabel1.setText("Código do Hóspede");

        jLabel2.setText("Código do Quarto");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(31, 31, 31)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(layout.createSequentialGroup()
                        .add(jButtonSalvar)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 90, Short.MAX_VALUE)
                        .add(jButtonFechar))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabelCodigo)
                            .add(jLabel3)
                            .add(jLabel4)
                            .add(jLabel5)
                            .add(jLabel6)
                            .add(jLabel1)
                            .add(jLabel2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jTextFieldCodigo)
                            .add(jTextFieldEntradaDia)
                            .add(jTextFieldEntradaHora)
                            .add(jTextFieldSaidaDia)
                            .add(jTextFieldSaidaHora, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                            .add(jTextFieldCodigoHospede)
                            .add(jTextFieldCodigoQuarto))))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextFieldCodigo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabelCodigo))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextFieldEntradaDia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextFieldEntradaHora, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextFieldSaidaDia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextFieldSaidaHora, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextFieldCodigoHospede, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jTextFieldCodigoQuarto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 31, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButtonSalvar)
                    .add(jButtonFechar))
                .add(72, 72, 72))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        AluguelDAO banco = new AluguelDAO();
        
        aluguel.setEntradaDia(jTextFieldEntradaDia.getText());
        aluguel.setEntradaHora(jTextFieldEntradaHora.getText());
        aluguel.setSaidaDia(jTextFieldSaidaDia.getText());
        aluguel.setSaidaHora(jTextFieldSaidaHora.getText());
        hospede.setCodigo(Integer.parseInt(jTextFieldCodigoHospede.getText()));
        quarto.setCodigo(Integer.parseInt(jTextFieldCodigoQuarto.getText()));
        aluguel.setHospede(hospede);
        aluguel.setQuarto(quarto);
        
        if (!editando) {
            aluguel.setCodigo(Integer.parseInt(jTextFieldCodigo.getText()));
            banco.adicionarAluguel(aluguel);
        } else {
            banco.updateAluguel(aluguel);
        }

        jTextFieldCodigo.setText("");
        jTextFieldEntradaDia.setText("");
        jTextFieldEntradaHora.setText("");
        jTextFieldSaidaDia.setText("");
        jTextFieldSaidaHora.setText("");
        jTextFieldCodigoHospede.setText("");
        jTextFieldCodigoQuarto.setText("");
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jTextFieldEntradaHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEntradaHoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEntradaHoraActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarAluguel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarAluguel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldCodigoHospede;
    private javax.swing.JTextField jTextFieldCodigoQuarto;
    private javax.swing.JTextField jTextFieldEntradaDia;
    private javax.swing.JTextField jTextFieldEntradaHora;
    private javax.swing.JTextField jTextFieldSaidaDia;
    private javax.swing.JTextField jTextFieldSaidaHora;
    // End of variables declaration//GEN-END:variables

}
